var product = [{
    "id": 0,
    "title": "",
    "price": "",
    "description": "",
    "brand": "",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/1665px-No-Image-Placeholder.svg.png",
     "fuel" : "",
     "capacity":"",
    "bodytype":"",
    "xpower":"",
    "cylinders":"",
    "seating":"",
    "mileage":"",
    "torque":"",
    "engin":""

}, {

    "id": 1,
    "title": "maruti-Alto K10",
    "price": 399000,
    "description": "Maruti Alto K10 is a 4 seater hatchback car with 1L petrol/CNG engine. Alto K10 price in India ranges between Rs. 3.99 Lakh to 5.96 Lakh and have got 2 star safety rating.     ",
    "brand": "Maruti Suzuki ",
    "image": "K10.webp",
    "fuel": "Petrol & CNG",
    "capacity":"27 Litres",
    "bodytype": "Hatchback",
    "xpower": "65.71bhp@5500rpm",
    "cylinders": "3 cylinder",
    "seating": "5 Seater",
    "mileage": "24.39 to 33.85 kmpl",
    "torque": "89Nm@3500rpm",
    "engin":"998 cc"

}, {
    "id": 2,
    "title": "maruti-Swift",
    "price": 920000,
    "description": "Maruti Swift is a 5 seater hatchback car with 1.2L petrol/CNG engine. Swift price in India ranges between Rs. 5.99 Lakh to 9.03 Lakh and have got 1 star safety rating.",
    "brand": "Maruti Suzuki",
    "image": "swift.webp",
    "fuel":"Petrol, CNG.",
    "capacity":"37 Litres",
    "bodytype":"Hatchback",
    "xpower":"88.50bhp@6000rpm",
    "cylinders":"4 cylinder",
    "seating":"5 seater",
    "mileage":"22.38 kmpl to 30.9 km/kg",
    "torque":"98.5Nm@4300rpm",
    "engin":"1197 cc"
}, {
    "id": 3,
    "title": "maruti-Wagonr",
    "price": 760000,
    "description": "The Maruti Suzuki Wagon R (or WagonR) is a city car manufactured and marketed by Suzuki through its subsidiary Maruti Suzuki primarily for the Indian market since 1999. 5.54 to 6.20 lakh.",
    "brand": "Maruti Suzuki",
    "image": "wagonr.webp",
    "fuel":"Petrol, CNG.",
    "capacity":"32 Liters.",
    "bodytype":"Hatchback",
    "xpower":"88.50bhp@6000rpm",
    "cylinders":"3 cylinder",
    "seating":"5 seater",
    "mileage":"23.56 kmpl to 34.05 km/kg.",
    "torque":"113Nm@4400rpm",
    "engin":"998 cc"
}, {
    "id": 4,
    "title": "maruti-Jimny",
    "price": 1500000,
    "description": "The key specifications of Jimny by Maruti Suzuki include the Ladder Frame Chassis, K15B Petrol Engine that generates peak power of 104.8 PS @ 6000 RPM and 134.2 Nm @ 4000 RPM of peak torque, ALLGRIP PRO that comes with Low Range Transfer Gear, and 3-Link Rigid Axle Suspension with Coil Spring to make sure it’s always ready to take the beaten path.15 to 16 lakhs    ",
    "brand": "Maruti Suzuki",
    "image": "jimny.webp",
    "fuel":"Petrol",
    "capacity":"40 Liters",
    "bodytype":"ladder frame chassis",
    "xpower":"103.39bhp@6000rpm",
    "cylinders":"4 cylinder",
    "seating":"4 seater",
    "mileage":"16.39 to 16.94 kmpl.",
    "torque":"134.2Nm@4000rpm",
    "engin":"1462 CC"
}, {
    "id": 5,
    "title": "maruti-Brezza",
    "price": 1423000,
    "description": "The Brezza is a 5 seater 4 cylinder car and has length of 3995 mm, width of 1790 mm and a wheelbase of 2500.12.5 to 14.3 lakh",
    "brand": "Maruti Suzuki",
    "image": "brezza.webp",
    "fuel":"petrol",
    "capacity":"48 Liters",
    "bodytype":"SUV",
    "xpower":"101.64bhp@6000rpm",
    "cylinders":"4 cylinder",
    "seating":"5 seater",
    "mileage":"17-20 km/l combined",
    "torque":"136.8Nm@4400rpm.",
    "engin":"1462 cc"
}, {
    "id": 6,
    "title": "maruti-Eeco",
    "price": 620000,
    "description": "The Eeco is a 5 seater 4 cylinder car and has length of 3675 mm, width of 1475 mm and a wheelbase of 2350.5.32 to 6.21 lakh.",
    "brand": "Maruti Suzuki",
    "image": "eeco.webp",
    "fuel":"petrol,CNG",
    "capacity":"32 Liters",
    "bodytype":"Wagon",
    "xpower":"70.67bhp@6000rpm",
    "cylinders":"4 Cylinder",
    "seating":"7 seater",
    "mileage":"20 km/l combined",
    "torque":"95Nm@3000rpm",
    "engin":"1197 cc"
}, {
    "id": 7,
    "title": "maruti-Ignis",
    "price": 890000,
    "description": "The Ignis is a 5 seater 4 cylinder car and has length of 3700 mm, width of 1690 mm and a wheelbase of 2435.5.20 to 8.10lakh.",
    "brand": "Maruti Suzuki",
    "image": "ignis.webp",
    "fuel":"Petrol",
    "capacity":"32 Liters",
    "bodytype":"Hatchback",
    "xpower":"61kW@6000rpm",
    "cylinders":"4 cylinder",
    "seating":"5 seater",
    "mileage":"21 km/l combined",
    "torque":"113Nm@4200rpm",
    "engin":" 1197 cc ."
}, {
    "id": 8,
    "title": "maruti-Fronx",
    "price": 596000,
    "description": "Realme C35 price in Pakistan is Rs. 32,999. Official dealers and warranty providers regulate the retail price of Realme mobile products in official warranty.",
    "brand": "Maruti Suzuki",
    "image": "fronx.webp",
    "fuel":"Petrol/CNG",
    "capacity":"37 Liters",
    "bodytype":"SUV",
    "xpower":"88.50bhp@6000rpm",
    "cylinders":"3 cylinder",
    "seating":"5 seater",
    "mileage":"20-23 km/l combined",
    "torque":"113Nm@4400rpm",
    "engin":"1197 cc"
}, {
    "id": 9,
    "title": "maruti-Ertiga",
    "price": 1330000,
    "description": "Maruti Ertiga is a 7 seater MUV car with 1.5 L petrol/CNG engine. Ertiga price in India ranges between Rs. 8.69 Lakh to 13.03 Lakh.",
    "brand": "Maruti Suzuki",
    "image": "ertiga.webp",
    "fuel":"petrol/CNG",
    "capacity":"45 Liters",
    "bodytype":"Wagon",
    "xpower":"101.64bhp@6000rpm",
    "cylinders":"4 cylinder",
    "seating":"7 seater",
    "mileage":"20-21 km/l combined",
    "torque":"136.8Nm@4400rpm",
    "engin":"1462 cc"

}, {
    "id": 10,
    "title": "maruti-Baleno",
    "price": 667000,
    "description": "The Baleno is a 5 seater 4 cylinder car and has length of 3990 mm, width of 1745 mm and a wheelbase of 2520 mm. 6.67 to 8.50lakhs",
    "brand": "Maruti Suzuki",
    "image": "Baleno.webp",
    "fuel":"petrol/CNG",
    "capacity":"37 Liters",
    "bodytype":"Hatchback",
    "xpower":"88.50bhp@6000rpm",
    "cylinders":"4 cylinder",
    "seating":"5 seater",
    "mileage":"22-23 km/l combined",
    "torque":"	113Nm@4400rpm",
    "engin":"1197 cc"
}, {
    "id": 11,
    "title": "Mahindra-Bolero",
    "price": "Rs.9.90 - 10.91 " ,
    "description":"The Mahindra Bolero has 1 Diesel Engine on offer. The Diesel engine is 1493 cc . It is available with Manual transmission.Depending upon the variant and fuel type the Bolero has a mileage of 16 kmpl & Ground clearance of Bolero",
    "brand": "Mahindra",
    "image": "bolero.webp",
    "fuel":"Diesel",
    "capacity":"60 Liters",
    "bodytype":"SUV",
    "xpower":"74.96bhp@3600rpm",
    "cylinders":"3 cylinder",
    "seating":"7 seater",
    "mileage":"16 kmpl.",
    "torque":"	210Nm@1600-2200rpm",
    "engin":"1493 cc"
},{
    "id": 12,
    "title": "Mahindra-Marazzo",
    "price": "Rs.14.39 - 16.80 ",
    "description": "The Mahindra Marazzo has 1 Diesel Engine on offer. The Diesel engine is 1497 cc . It is available with Manual transmission.Depending upon the variant and fuel type the Marazzo has a mileage of 17.3 kmpl . The Marazzo is a 8 seater 4 cylinder car and has length of 4585 mm, width of 1866 mm and a wheelbase of 2750.",
    "brand": "Mahindra",
    "image": "marazzo.webp",
     "fuel" : "Diesel",
     "capacity":"45 Liters",
    "bodytype":"MUV",
    "xpower":"120.96bhp@3500rpm",
    "cylinders":"4 cylinder",
    "seating":"8 seater",
    "mileage":"17.3 kmpl",
    "torque":"300Nm@1750-2500rpm",
    "engin":"1497 cc"
},{
    "id": 13,
    "title": "Mahindra-Scorpio",
    "price": "Rs.13.59 - 17.35",
    "description": "The Mahindra Scorpio has 1 Diesel Engine on offer. The Diesel engine is 2184 cc . It is available with Manual transmission.Depending upon the variant and fuel type the Scorpio has a mileage of . The Scorpio is a 7 seater 4 cylinder car and has length of 4456 mm, width of 1820 mm and a wheelbase of 2750.",
    "brand": "Mahindra",
    "image": "scorpio.webp",
     "fuel" : "Diesel",
     "capacity":"60 Litres",
    "bodytype":"SUV",
    "xpower":"130bhp@3750rpm",
    "cylinders":"4 cylinder",
    "seating":"7,9 seater",
    "mileage":"15 kmpl",
    "torque":"300Nm@1600-2800rpm",
    "engin":"2184 cc"
},{
    "id": 14,
    "title": "Mahindra-TUV300",
    "price": "Rs.8.54 - 10.81",
    "description": "The Mahindra TUV 300 has 1 Diesel Engine on offer. The Diesel engine is 1493 cc . It is available with Manual transmission.Depending upon the variant and fuel type the TUV 300 has a mileage of 18.49 kmpl & Ground clearance of TUV 300 is 184 mm. The TUV 300 is a 7 seater 3 cylinder car and has length of 3995mm, width of 1795mm and a wheelbase of 2680mm.",
    "brand": "Mahindra",
    "image": "tuv300.webp",
     "fuel" : "Diesel",
     "capacity":"60 Litres",
    "bodytype":"SUV",
    "xpower":"100bhp@3750rpm",
    "cylinders":"3 cylinder",
    "seating":"7 seater",
    "mileage":"18.49 kmpl.",
    "torque":"240Nm@1600-2800rpm",
    "engin":"1493 cc"
},{
    "id": 15,
    "title": "Mahindra-XUV300",
    "price": "Rs.7.99 - 14.76 Lakh",
    "description": "The Mahindra XUV300 has 1 Diesel Engine and 1 Petrol Engine on offer. The Diesel engine is 1497 cc while the Petrol engine is 1197 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the XUV300 has a mileage of 20.1 kmpl . The XUV300 is a 5 seater 4 cylinder car and has length of 3995 mm, width of 1821 mm and a wheelbase of 2600 mm.",
    "brand": "Mahindra",
    "image": "xuv300.webp",
    "fuel" : "Diesel",
    "capacity":"42 Litres",
    "bodytype":"SUV",
    "xpower":"115.05bhp@3750rpm",
    "cylinders":"4 cylinder",
    "seating":"5 seater",
    "mileage":"19.7 kmpl",
    "torque":"300Nm@1500-2500rpm",
    "engin":"1497 cc"
},{
    "id": 16,
    "title": "Mahindra-XUV500",
    "price": "Rs.12 - 20.07 ",
    "description": "The Mahindra XUV500 has 2 Diesel Engine and 1 Petrol Engine on offer. The Diesel engine is 2179 cc and 1997 cc while the Petrol engine is 2179 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the XUV500 has a mileage of 16 kmpl & Ground clearance of XUV500 is 200 mm. The XUV500 is a 7 seater 4 cylinder car and has length of 4585mm, width of 1890mm and a wheelbase of 2700mm.",
    "brand": "Mahindra",
    "image": "xuv500.webp",
    "fuel" : "Diesel",
    "capacity":"70 Litres",
    "bodytype":"SUV",
    "xpower":"152.87bhp@3750rpm",
    "cylinders":"4 cylinder",
    "seating":"7 seater",
    "mileage":"15.1 kmpl",
    "torque":"360Nm@1750-2800rpm",
    "engin":"2179 cc"
},{
    "id": 17,
    "title": "Mhindra-XUV700",
    "price": "Rs.13.99 - 26.99 ",
    "description": "The Mahindra XUV700 has 1 Diesel Engine and 1 Petrol Engine on offer. The Diesel engine is 2198 cc while the Petrol engine is 1999 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the XUV700 has a mileage of 17 kmpl . The XUV700 is a 7 seater 4 cylinder car and has length of 4695 mm, width of 1890 mm and a wheelbase of 2829",
    "brand": "Mahindra",
    "image": "xuv700.webp",
    "fuel" : "Diesel",
    "capacity":"60 Litres",
    "bodytype":"SUV",
    "xpower":"182.38bhp@3500rpm",
    "cylinders":"4 cylinder",
    "seating":"5, 6, 7",
    "mileage":"16.57 kmpl",
    "torque":"450Nm@1750-2800rpm",
    "engin":"2198 cc"
},{
    "id": 18,
    "title": "Mahindra-Thar",
    "price": "Rs.11.25 - 17.60 Lakh",
    "description": "The Mahindra Thar has 2 Diesel Engine and 1 Petrol Engine on offer. The Diesel engine is 2184 cc and 1497 cc while the Petrol engine is 1997 cc . It is available with Automatic & Manual transmission.Depending upon the variant and fuel type the Thar has a mileage of 15.2 kmpl & Ground clearance of Thar is 226 mm. The Thar is a 4 seater 4 cylinder car and has length of 3985 mm, width of 1820 mm and a wheelbase of 2450 mm.",
    "brand": "Mahindra",
    "image": "thar.webp",
    "fuel" : "Diesel/petrol",
    "capacity":"57 Litres",
    "bodytype":"SUV",
    "xpower":"130.07bhp@3750rpm",
    "cylinders":"4 cylinder",
    "seating":"4 seater",
    "mileage":"9 kmpl",
    "torque":"300Nm@1600-2800rpm",
    "engin":"2184 cc"
},{
    "id": 19,
    "title": "TATA-Safari",
    "price": "Rs.16.19 - 27.34 ",
    "description": "The Tata Safari has 1 Diesel Engine on offer. The Diesel engine is 1956 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the Safari has a mileage of 16.3 kmpl . The Safari is a 6 seater 4 cylinder car and has length of 4668 mm, width of 1922 mm and a wheelbase of 2500.",
    "brand": "TATA",
    "image": "safari.webp",
    "fuel" : "Diesel",
    "capacity":"50 Litres",
    "bodytype":"SUV",
    "xpower":"350Nm@1750-2500rpm",
    "cylinders":"4 cylinder",
    "seating":"6, 7 seater",
    "mileage":"15-16 km/l combined",
    "torque":"167.62bhp@3750rpm",
    "engin":"1956 cc"
},{
    "id": 20,
    "title": "TATA-Harrier",
    "price": "Rs.15.49 - 26.44 Lakh",
    "description": "The Tata Harrier has 1 Diesel Engine on offer. The Diesel engine is 1956 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the Harrier has a mileage of 16.8 kmpl . The Harrier is a 5 seater 4 cylinder car and has length of 4605 mm, width of 1922 mm and a wheelbase of 2850.",
    "brand": "TATA",
    "image": "harrier.webp",
    "fuel" : "Diesel",
    "capacity":"50 Liters",
    "bodytype":"SUV",
    "xpower":"167.62bhp@3750rpm",
    "cylinders":"4 cylinder",
    "seating":"5 seater",
    "mileage":"15-17 km/l combined",
    "torque":"350Nm@1750-2500rpm",
    "engin":"1956 cc."
},{
    "id": 21,
    "title": "TATA-Altroz",
    "price": "Rs.6.65 - 10.80 Lakh",
    "description": "The Tata Altroz has 1 Diesel Engine, 1 Petrol Engine and 1 CNG Engine on offer. The Diesel engine is 1497 cc, the Petrol engine is 1199 cc while the CNG engine is 1199 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the Altroz has a mileage of 18.05 kmpl to 26.2 km/kg & Ground clearance of Altroz is 165 mm. The Altroz is a 5 seater 4 cylinder car and has length of 3990 mm, width of 1755 mm and a wheelbase of 2501 mm.",
    "brand": "TATA",
    "image": "altroz.webp",
    "fuel" : "Diesel",
    "capacity":"37 Litres",
    "bodytype":"Hatchback",
    "xpower":"88.77bhp@4000rpm",
    "cylinders":"4 cylinder",
    "seating":"5 seater",
    "mileage":"23.64 kmpl",
    "torque":"200Nm@1250-3000rpm",
    "engin":"1497 cc"
},{
    "id": 22,
    "title": "TATA-Nexon",
    "price": "Rs.8.15 - 15.60 ",
    "description": "The Tata Nexon has 1 Diesel Engine and 1 Petrol Engine on offer. The Diesel engine is 1497 cc while the Petrol engine is 1199 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the Nexon has a mileage of 17.01 to 24.08 kmpl & Ground clearance of Nexon is 208 mm. The Nexon is a 5 seater 4 cylinder car and has length of 3995 mm, width of 1804 mm and a wheelbase of 2498 mm.",
    "brand": "TATA",
    "image": "nexon.webp",
    "fuel" : "Diesel",
    "capacity":"44 Litres",
    "bodytype":"SUV",
    "xpower":"113.31bhp@3750rpm",
    "cylinders":"4 cylinder",
    "seating":"5 seater",
    "mileage":"24.08 kmpl",
    "torque":"260Nm@1500-2750rpm",
    "engin":"1497 cc"
},{
    "id": 23,
    "title": "TATA-Punch",
    "price": "Rs.6.13 - 10.20 Lakh",
    "description": "The Tata Punch has 1 Petrol Engine and 1 CNG Engine on offer. The Petrol engine is 1199 cc while the CNG engine is 1199 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the Punch has a mileage of 18.8 kmpl to 26.99 km/kg & Ground clearance of Punch is 187 mm. The Punch is a 5 seater 3 cylinder car and has length of 3827 mm, width of 1742 mm and a wheelbase of 2445 mm.",
    "brand": "TATA",
    "image": "punch.webp",
    "fuel" : "Petrol",
    "capacity":"37 Litres",
    "bodytype":"SUV",
    "xpower":"86.63bhp@6000rpm",
    "cylinders":"3 cylinder",
    "seating":"5 seater",
    "mileage":"18.8 kmpl",
    "torque":"115Nm@3250+/-100rpm",
    "engin":"1199 cc"
},{
    "id": 24,
    "title": "TATA-Tiago",
    "price": "Rs.5.65 - 8.90 ",
    "description": "The Tata Tiago has 1 Petrol Engine and 1 CNG Engine on offer. The Petrol engine is 1199 cc while the CNG engine is 1199 cc . It is available with Automatic & Manual transmission.Depending upon the variant and fuel type the Tiago has a mileage of 19 kmpl to 26.49 km/kg & Ground clearance of Tiago is 168 mm. The Tiago is a 5 seater 3 cylinder car and has length of 3765 mm, width of 1677 mm and a wheelbase of 2400 mm.",
    "brand": "TATA",
    "image": "tiago.webp",
    "fuel" : "Petrol",
    "capacity":"60 Litres",
    "bodytype":"Hatchback",
    "xpower":"72.41bhp@6000rpm",
    "cylinders":"3 cylinder",
    "seating":"5 seater",
    "mileage":"26.49 km/kg",
    "torque":"95Nm@3500rpm",
    "engin":"1199 cc"
},{
    "id": 25,
    "title": "TATA-Tigor",
    "price": "Rs.6.30 - 9.55",
    "description": "The Tata Tigor has 1 Petrol Engine and 1 CNG Engine on offer. The Petrol engine is 1199 cc while the CNG engine is 1199 cc . It is available with Automatic & Manual transmission.Depending upon the variant and fuel type the Tigor has a mileage of 19.28 kmpl to 26.49 km/kg . The Tigor is a 5 seater 3 cylinder car and has length of 3993 mm, width of 1677 mm and a wheelbase of 2450 mm.",
    "brand": "TATA",
    "image": "tigor.webp",
    "fuel" : "Petrol",
    "capacity":"70 Litres",
    "bodytype":"Sedan",
    "xpower":"72.41bhp@6000rpm",
    "cylinders":"3 cylinder",
    "seating":"5 seater",
    "mileage":"19.6 km/kg",
    "torque":"95Nm@3500rpm",
    "engin":"1199 cc"
},{
    "id": 26,
    "title": "HYUNDAI-Alcazar",
    "price": "Rs.16.77 - 21.28",
    "description": "The Hyundai Alcazar has 1 Diesel Engine and 1 Petrol Engine on offer. The Diesel engine is 1493 cc while the Petrol engine is 1482 cc . It is available with Automatic & Manual transmission.Depending upon the variant and fuel type the Alcazar has a mileage of 24.5 kmpl . The Alcazar is a 7 seater 4 cylinder car and has length of 4500 mm, width of 1790 mm and a wheelbase of 2760 mm.",
    "brand": "Hyundai",
    "image": "alcazar.webp",
    "fuel" : "Diesel",
    "capacity":"50 Litres",
    "bodytype":"SUV",
    "xpower":"113.98bhp@4000rpm",
    "cylinders":"4 cylinder",
    "seating":"6,7 seater",
    "mileage":"23.8 kmpl",
    "torque":"250Nm@1500-2750rpm",
    "engin":"1493 cc"
},{
    "id": 27,
    "title": "HYUNDAI-Creta",
    "price": "Rs.11 - 20.15 ",
    "description": "The Hyundai Creta has 1 Diesel Engine and 2 Petrol Engine on offer. The Diesel engine is 1493 cc while the Petrol engine is 1497 cc and 1482 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the Creta has a mileage of 17.4 to 21.8 kmpl & Ground clearance of Creta is 190 mm. The Creta is a 5 seater 4 cylinder car and has length of 4330 mm, width of 1790 mm and a wheelbase of 2610 mm.",
    "brand": "Hyundai",
    "image": "creta.webp",
    "fuel" : "Petrol",
    "capacity":"50 Litres",
    "bodytype":"SUV",
    "xpower":"157.57bhp@5500rpm",
    "cylinders":"4 cylinder",
    "seating":"5 seater",
    "mileage":"18.4 kmpl",
    "torque":"253Nm@1500-3500rpm",
    "engin":"1482 cc"
},{
    "id": 28,
    "title": "HYUNDAI-Elantra",
    "price": "Rs.15 - 21.13",
    "description": "he Hyundai Elantra has 2 Diesel Engine and 1 Petrol Engine on offer. The Diesel engine is 1582 cc and 1493 cc while the Petrol engine is 1999 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the Elantra has a mileage of 14.62 kmpl & Ground clearance of Elantra is 167 mm. The Elantra is a 5 seater 4 cylinder car and has length of 4620mm, width of 1800mm and a wheelbase of 2700mm.",
    "brand": "Hyundai",
    "image": "elantra.webp",
    "fuel" : "Diesel",
    "capacity":"50 Litres",
    "bodytype":"Sedan",
    "xpower":"113.45bhp@4000rpm",
    "cylinders":"4 cylinder",
    "seating":"5 seater",
    "mileage":"14.62 kmpl",
    "torque":"250nm@1500-2750rpm",
    "engin":"1493 cc"
},{
    "id": 29,
    "title": "HYUNDAI-I10",
    "price": "Rs.3.79 - 6.55",
    "description": "The Hyundai i10 has 2 Petrol Engine and 1 LPG Engine on offer. The Petrol engine is 1086 cc and 1197 cc while the LPG engine is 1086 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the i10 has a mileage of 16.95 to 20.36 kmpl & Ground clearance of i10 is 165 mm. The i10 is a 5 seater 4 cylinder car and has length of 3585mm, width of 1595mm and a wheelbase of 2380mm.",
    "brand": "Hyundai",
    "image": "i10.webp",
    "fuel" : "Petrol",
    "capacity":"35 Litres",
    "bodytype":"Hatchback",
    "xpower":"78.9bhp@6000rpm",
    "cylinders":"4 cylinder",
    "seating":"5 seater",
    "mileage":"16.95 kmpl",
    "torque":"111.8Nm@4000rpm",
    "engin":"1197 cc"
},{
    "id": 30,
    "title": "HYUNDAI-I20",
    "price": "Rs.7.04 - 11.21",
    "description": "The Hyundai i20 has 1 Petrol Engine on offer. The Petrol engine is 1197 cc . It is available with Automatic & Manual transmission.Depending upon the variant and fuel type the i20 has a mileage of 16 to 20 kmpl . The i20 is a 5 seater 4 cylinder car and has length of 3995 mm, width of 1775 mm and a wheelbase of 2580 mm.",
    "brand": "Hyundai",
    "image": "i20.webp",
    "fuel" : "Petrol",
    "capacity":"37 Litres",
    "bodytype":"Hatchback",
    "xpower":"86.76bhp@6000rpm",
    "cylinders":"4 cylinder",
    "seating":"5 seater",
    "mileage":"20 kmpl",
    "torque":"114.7Nm@4200rpm",
    "engin":"1197 cc"
},{
    "id": 31,
    "title": "HYUNDAI-Palisade",
    "price": "Rs.40",
    "description": "The Hyundai Palisade has 1 Diesel Engine on offer. The Diesel engine is 3800 cc . It is available with the Automatic transmission.",
    "brand": "Hyundai",
    "image": "Palisade.webp",
    "fuel" : "Diesel",
    "capacity":"18.8 gallons",
    "bodytype":"SUV",
    "xpower":"287bhp@6000rpm",
    "cylinders":"4 cylinder",
    "seating":"7 seater",
    "mileage":"13.30kmpl",
    "torque":"441Nm @ 1750 - 2750rpm",
    "engin":"3800 cc"
},{
    "id": 32,
    "title": "HYUNDAI-Venue",
    "price": "Rs.7.94 - 13.48",
    "description": "The Hyundai Venue has 1 Diesel Engine and 2 Petrol Engine on offer. The Diesel engine is 1493 cc while the Petrol engine is 1197 cc and 998 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the Venue has a mileage of 24.2 kmpl . The Venue is a 5 seater 3 cylinder car and has length of 3995 mm, width of 1770 mm and a wheelbase of 2500 mm.",
    "brand": "Hyundai",
    "image": "venue.webp",
    "fuel" : "Petrol",
    "capacity":"45 Litres",
    "bodytype":"SUV",
    "xpower":"118.41bhp@6000rpm",
    "cylinders":"3 cylinder",
    "seating":"5 seater",
    "mileage":"18.31 kmpl",
    "torque":"118.41bhp@6000rpm",
    "engin":"998 cc"
},{
    "id": 33,
    "title": "HYUNDAI-Verna",
    "price": "Rs.11 - 17.42",
    "description": "The Hyundai Verna has 2 Petrol Engine on offer. The Petrol engine is 1497 cc and 1482 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the Verna has a mileage of 18.6 to 20.6 kmpl . The Verna is a 5 seater 4 cylinder car and has length of 4535 mm, width of 1765 mm and a wheelbase of 2670 mm.",
    "brand": "Hyundai",
    "image": "verna.webp",
    "fuel" : "petrol",
    "capacity":"45 Litres",
    "bodytype":"Sedan",
    "xpower":"157.57bhp@5500rpm",
    "cylinders":"4 cylinder",
    "seating":" 5 seater",
    "mileage":"20.6 kmpl",
    "torque":"253Nm@1500-3500rpm",
    "engin":"1482 cc"
},{
    "id": 34,
    "title": "Toyata-Camry",
    "price": "Rs.46.17",
    "description": "The Toyota Camry has 1 Petrol Engine on offer. The Petrol engine is 2487 cc . It is available with Automatic transmission.Depending upon the variant and fuel type the Camry has a mileage of . The Camry is a 5 seater 4 cylinder car and has length of 4885 mm, width of 1840 mm and a wheelbase of 2807.",
    "brand": "Toyata",
    "image": "camry.webp",
    "fuel" : "Secondary Fuel Type Electric/ petrol",
    "capacity":"50 Litres",
    "bodytype":"Sedan",
    "xpower":"175.67bhp@5700rpm",
    "cylinders":"4 cylinder",
    "seating":"5 seater",
    "mileage":"23 km/l combined",
    "torque":"221Nm@3600to5200rpm",
    "engin":"2487 cc"
},{
    "id": 35,
    "title": "Toyata-Fortuner",
    "price": "Rs.33.43 - 51.44",
    "description": "The Toyota Fortuner has 1 Diesel Engine and 1 Petrol Engine on offer. The Diesel engine is 2755 cc while the Petrol engine is 2694 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the Fortuner has a mileage of 10 kmpl . The Fortuner is a 7 seater 4 cylinder car and has length of 4795 mm, width of 1855 mm and a wheelbase of 2750.",
    "brand": "Toyata",
    "image": "fortuner.webp",
    "fuel" : "Diesel",
    "capacity":"80 liters",
    "bodytype":"SUV",
    "xpower":"201.15bhp@3000-3400rpm",
    "cylinders":"4 cylinder",
    "seating":"7 seater",
    "mileage":"10 to 14.4kmpl",
    "torque":"500Nm@1600-2800rpm",
    "engin":"2755 cc"
},{
    "id": 36,
    "title": "Toyata-Glanza",
    "price": "Rs.6.86 - 10",
    "description": "The Toyota Glanza has 1 Petrol Engine and 1 CNG Engine on offer. The Petrol engine is 1197 cc while the CNG engine is 1197 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the Glanza has a mileage of 22.35 kmpl to 30.61 km/kg . The Glanza is a 5 seater 4 cylinder car and has length of 3990 mm, width of 1745 mm and a wheelbase of 2780.",
    "brand": "Toyata",
    "image": "glanza.webp",
    "fuel" : "Petrol",
    "capacity":"37 Litres",
    "bodytype":"Hatchback",
    "xpower":"88.50bhp@6000rpm",
    "cylinders":"4 cylinder",
    "seating":"5 seater",
    "mileage":"22.94 kmpl",
    "torque":"113Nm@4400rpm",
    "engin":"1197 cc"
},{
    "id": 37,
    "title": "Toyota-Innova Crysta",
    "price": "Rs.19.99 - 26.30 ",
    "description": "The Toyota Innova Crysta has 1 Diesel Engine on offer. The Diesel engine is 2393 cc . It is available with Manual transmission.Depending upon the variant and fuel type the Innova Crysta has a mileage of . The Innova Crysta is a 7 seater 4 cylinder car and has length of 4735 mm, width of 1830 mm and a wheelbase of 2750 mm.",
    "brand": "Toyata",
    "image": "innova.webp",
    "fuel" : "Petrol/Diesel",
    "capacity":"55 Litres",
    "bodytype":"MUV",
    "xpower":"343Nm@1400-2800rpm",
    "cylinders":"4 cylinder",
    "seating":"7,8 seater",
    "mileage":"8 to 12kmpl",
    "torque":"147.51bhp@3400rpm",
    "engin":"2393 cc"
},{
    "id": 38,
    "title": "Toyota-Innova Hycross",
    "price": "Rs.19.77 - 30.68 ",
    "description": "The Toyota Innova Hycross has 1 Petrol Engine on offer. The Petrol engine is 1987 cc . It is available with Automatic transmission.Depending upon the variant and fuel type the Innova Hycross has a mileage of 16.13 to 23.24 kmpl . The Innova Hycross is a 7 seater 4 cylinder car and has length of 4755 mm, width of 1845 mm and a wheelbase of 2450.",
    "brand": "Toyata",
    "image": "hycross.webp",
    "fuel" : "Secondary Fuel Type Electric/Petrol",
    "capacity":"52 Litres",
    "bodytype":"MUV",
    "xpower":"183.72bhp@6600rpm",
    "cylinders":"4",
    "seating":"7,8",
    "mileage":"23.24 kmpl",
    "torque":"188Nm@4398-5196rpm",
    "engin":"1987 cc"
},{
    "id": 39,
    "title": "Toyota-Land Cruiser 300",
    "price": "Rs.2,10,00000",
    "description": "The Toyota Land Cruiser 300 has 1 Diesel Engine on offer. The Diesel engine is 3346 cc . It is available with Automatic transmission.Depending upon the variant and fuel type the Land Cruiser 300 has a mileage of 11 kmpl . The Land Cruiser 300 is a 5 seater 6 cylinder car and has length of 4685 mm, width of 1980 mm and a wheelbase of 2740.",
    "brand": "Toyata",
    "image": "landcruiser 300.webp",
    "fuel" : "Diesel",
    "capacity":"110 Litres",
    "bodytype":"SUV",
    "xpower":"304.41bhp@4000rpm",
    "cylinders":"6 cylinder",
    "seating":"5 seater",
    "mileage":"11 kmpl",
    "torque":"700Nm@1600-2600rpm",
    "engin":"3346 cc"
},{
    "id": 40,
    "title": "Toyota-Rumion",
    "price": "Rs.10.44 - 13.73",
    "description": "The Toyota Rumion has 1 Petrol Engine and 1 CNG Engine on offer. The Petrol engine is 1462 cc while the CNG engine is 1462 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the Rumion has a mileage of 20.11 kmpl to 26.11 km/kg . The Rumion is a 7 seater 4 cylinder car and has length of 4420 mm, width of 1735 mm and a wheelbase of 2498.",
    "brand": "Toyota ",
    "image": "rumion.webp",
    "fuel" : "Petrol",
    "capacity":"45 Litres",
    "bodytype":"MUV",
    "xpower":"101.64bhp@6000rpm",
    "cylinders":"4 cylinder",
    "seating":"7 seater",
    "mileage":"20.11 kmpl",
    "torque":"136.8Nm@4400rpm",
    "engin":"1462 cc"
},{
    "id": 41,
    "title": "Toyata-Supra",
    "price": "Rs.85",
    "description": "The Toyota Supra has 1 Petrol Engine on offer. The Petrol engine is 1998 cc . It is available with the Automatic transmission.",
    "brand": "Toyata",
    "image": "supraa.webp",
    "fuel" : "Petrol",
    "capacity":"",
    "bodytype":"Coupe",
    "xpower":"",
    "cylinders":"",
    "seating":"2 seater",
    "mileage":"13.2kmpl",
    "torque":"",
    "engin":"1998 cc"
    },{
    "id": 42,
    "title": "Honda-Amaze",
    "price": "Rs.7.16 - 9.92",
    "description": "The Honda Amaze has 1 Petrol Engine on offer. The Petrol engine is 1199 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the Amaze has a mileage of 18.3 to 18.6 kmpl . The Amaze is a 5 seater 4 cylinder car and has length of 3995 mm, width of 1695 mm and a wheelbase of 2741.",
    "brand": "Honda",
    "image": "amaze.webp",
    "fuel" : "Petrol",
    "capacity":"35 Litres",
    "bodytype":"Sedan",
    "xpower":"88.50bhp@6000rpm",
    "cylinders":"4 cylinder",
    "seating":"5 seater",
    "mileage":"18.3 kmpl",
    "torque":"88.50bhp@6000rpm",
    "engin":"1199 cc"
    },{
    "id": 43,
    "title": "Honda-Brio",
    "price": "Rs.4.73 - 6.82",
    "description": "The Honda Brio has 1 Petrol Engine on offer. The Petrol engine is 1198 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the Brio has a mileage of 16.5 to 22 kmpl & Ground clearance of Brio is 165 mm. The Brio is a 5 seater 4 cylinder car and has length of 3610mm, width of 1680mm and a wheelbase of 2345mm.",
    "brand": "Honda",
    "image": "brio.webp",
    "fuel" : "Petrol",
    "capacity":"35 Litres",
    "bodytype":"Hatchback",
    "xpower":"86.8bhp@6000rpm",
    "cylinders":"4 cylinder",
    "seating":"5 seater",
    "mileage":"16.5 kmpl",
    "torque":"109Nm@4500rpm",
    "engin":"1198 cc"
    },{
    "id": 44,
    "title": "Honda City",
    "price": "Rs.11.71 - 16.19",
    "description": "The Honda City has 1 Petrol Engine on offer. The Petrol engine is 1498 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the City has a mileage of 17.8 to 18.4 kmpl . The City is a 5 seater 4 cylinder car and has length of 4583 mm, width of 1748 mm and a wheelbase of 5209.",
    "brand": "Honda",
    "image": "city.webp",
    "fuel" : "Petrol",
    "capacity":"40 Litres",
    "bodytype":"Sedan",
    "xpower":"119.35bhp@6600rpm",
    "cylinders":"4 cylinder",
    "seating":"5 seater",
    "mileage":"18.4 kmpl",
    "torque":"145Nm@4300rpm",
    "engin":"1498 cc"
    },{
    "id": 45,
    "title": "Honda-Civic",
    "price": "Rs.15 - 22.35",
    "description": "The Honda Civic has 1 Diesel Engine and 1 Petrol Engine on offer. The Diesel engine is 1597 cc while the Petrol engine is 1799 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the Civic has a mileage of 16.5 to 26.8 kmpl . The Civic is a 5 seater 4 cylinder car and has length of 4656 mm, width of 1799 mm and a wheelbase of 2700 mm.",
    "brand": "Honda",
    "image": "civic.webp",
    "fuel" : "Diesel",
    "capacity":"47 Litres",
    "bodytype":"Sedan",
    "xpower":"118bhp@4000rpm",
    "cylinders":"4 cylinder",
    "seating":"5 seater",
    "mileage":"26.8 kmpl",
    "torque":"300Nm@2000rpm",
    "engin":"1597 cc"
    },{
    "id": 46,
    "title": "Honda Elevate",
    "price": "Rs.11.58 - 16.20",
    "description": "The Honda Elevate has 1 Petrol Engine on offer. The Petrol engine is 1498 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the Elevate has a mileage of 15.31 to 16.92 kmpl . The Elevate is a 5 seater 4 cylinder car and has length of 4312 mm, width of 1790 mm and a wheelbase of 2650.",
    "brand": "Honda",
    "image": "elevate.webp",
    "fuel" : "Petrol",
    "capacity":"40 Litres",
    "bodytype":"SUV",
    "xpower":"119.35bhp@6600rpm",
    "cylinders":"4 cylinder",
    "seating":"5 seater",
    "mileage":"16.92 kmpl",
    "torque":"145Nm@4300rpm",
    "engin":"1498 cc"
    },{
    "id": 47,
    "title": "Honda Jazz",
    "price": "Rs.8.01 - 10.32",
    "description": "The Honda Jazz has 1 Petrol Engine on offer. The Petrol engine is 1199 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the Jazz has a mileage of 17.1 kmpl . The Jazz is a 5 seater 4 cylinder car and has length of 3989mm, width of 1694 and a wheelbase of 2530.",
    "brand": "Honda",
    "image": "jazz.webp",
    "fuel" : "Petrol",
    "capacity":"40 Litres",
    "bodytype":"Hatchback",
    "xpower":"88.50bhp@6000rpm",
    "cylinders":"4 cylinder",
    "seating":" 5 seater",
    "mileage":"17.1 kmpl",
    "torque":"110Nm@4800rpm",
    "engin":"1199 cc"
    },{
    "id": 48,
    "title": "Volkswagen-Ameo",
    "price": "Rs.5.32 - 10 ",
    "description": "The Volkswagen Ameo has 1 Diesel Engine and 2 Petrol Engine on offer. The Diesel engine is 1498 cc while the Petrol engine is 999 cc and 1198 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the Ameo has a mileage of 17 to 22 kmpl & Ground clearance of Ameo is 163 mm. The Ameo is a 5 seater 4 cylinder car and has length of 3995mm, width of 1682mm and a wheelbase of 2470mm.",
    "brand": "Volkswagen",
    "image": "ameo.webp",
    "fuel" : "Diesel",
    "capacity":"45 Litres",
    "bodytype":"Sedan",
    "xpower":"108.495bhp@4000rpm",
    "cylinders":"4 cylinder",
    "seating":"5 seater",
    "mileage":"22 kmpl",
    "torque":"250Nm@1500-3000rpm",
    "engin":"1498 cc"
    },{
    "id": 49,
    "title": "Volkswagen-Jetta",
    "price": "Rs.14.78 - 20.90 ",
    "description": "The Volkswagen Jetta has 1 Diesel Engine and 1 Petrol Engine on offer. The Diesel engine is 1968 cc while the Petrol engine is 1390 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the Jetta has a mileage of 14.69 to 19.33 kmpl & Ground clearance of Jetta is 159 mm. The Jetta is a 5 seater 4 cylinder car and has length of 4659mm, width of 1778mm and a wheelbase of 2648mm.",
    "brand": "Volkswagen ",
    "image": "jetta.webp",
    "fuel" : "diesel/petrol",
    "capacity":"55 Litres",
    "bodytype":"Sedan",
    "xpower":"138.03bhp@4200rpm",
    "cylinders":"4 cylinder",
    "seating":"5 seater",
    "mileage":"16.96 kmpl",
    "torque":"320Nm@1750-2500rpm",
    "engin":"1968 cc"
    },{
    "id": 50,
    "title": "Volkswagen-Passat",
    "price": "Rs.30.21 - 33.22",
    "description": "The Volkswagen Passat has 1 Diesel Engine on offer. The Diesel engine is 1968 cc . It is available with Automatic transmission.Depending upon the variant and fuel type the Passat has a mileage of 17.42 kmpl . The Passat is a 5 seater 4 cylinder car and has length of 4767mm, width of 1832mm and a wheelbase of 2786mm.",
    "brand": "Volkswagen ",
    "image": "passat.webp",
    "fuel" : "Diesel",
    "capacity":"66 Litres",
    "bodytype":"Sedan",
    "xpower":"175bhp@3600-4000rpm",
    "cylinders":"4 cylinder",
    "seating":"5 seater",
    "mileage":"17.42 kmpl",
    "torque":"350Nm@1500-3500rpm",
    "engin":"1968 cc"
},{
    "id": 51,
    "title": "Volkswagen-Polo",
    "price": "Rs.5.83 - 10.25",
    "description": "The Volkswagen Polo has 1 Diesel Engine and 2 Petrol Engine on offer. The Diesel engine is 1498 cc while the Petrol engine is 999 cc and 1197 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the Polo has a mileage of 21.49 kmpl & Ground clearance of Polo is 165 mm. The Polo is a 5 seater 3 cylinder car and has length of 3971mm, width of 1682mm and a wheelbase of 2470mm.",
    "brand": "Volkswagen",
    "image": "polo.webp",
    "fuel" : "Diesel/petrol",
    "capacity":"45 Litres",
    "bodytype":"Hatchback",
    "xpower":"108.62bhp@5000-5500rpm",
    "cylinders":"3 cylinder",
    "seating":"5 seater",
    "mileage":"15.16 kmpl",
    "torque":"175nm@1750-4000rpm",
    "engin":"999 cc"
},{
    "id": 52,
    "title": "Volkswagen-Taigun",
    "price": "Rs.11.70 - 20 ",
    "description": "The Volkswagen Taigun has 2 Petrol Engine on offer. The Petrol engine is 999 cc and 1498 cc . It is available with Automatic & Manual transmission.Depending upon the variant and fuel type the Taigun has a mileage of 17.88 to 20.08 kmpl & Ground clearance of Taigun is 188 mm. The Taigun is a 5 seater 4 cylinder car and has length of 4221 mm, width of 1760 mm and a wheelbase of 2741.",
    "brand": "Volkswagen",
    "image": "taigun.webp",
    "fuel" : "Petrol",
    "capacity":"50 Litres",
    "bodytype":"50 Litres",
    "xpower":"147.51bhp@5000-6000rpm",
    "cylinders":"4 cylinder",
    "seating":"5 seater",
    "mileage":"17.88 kmpl",
    "torque":"250Nm@1600-3500rpm",
    "engin":"1498 cc"
},{
    "id": 53,
    "title": "Volkswagen-Tiguan",
    "price": "Rs.35.17 ",
    "description": "The Volkswagen Tiguan has 1 Petrol Engine on offer. The Petrol engine is 1984 cc . It is available with Automatic transmission.Depending upon the variant and fuel type the Tiguan has a mileage of 12.65 kmpl . The Tiguan is a 5 seater 4 cylinder car and has length of 4509 mm, width of 1839 mm and a wheelbase of 2950.",
    "brand": "Volkswagen ",
    "image": "tiugan.webp",
    "fuel" : "Petrol",
    "capacity":"60 Litres",
    "bodytype":"SUV",
    "xpower":"187.74bhp@4200-6000rpm",
    "cylinders":"4 cylinder",
    "seating":"5 seater",
    "mileage":"12.65 kmpl",
    "torque":"320Nm@1500-4100rpm",
    "engin":"1984 cc"
},{
    "id": 54,
    "title": "Volkswagen-Vento",
    "price": "Rs.8.69 - 14.79 ",
    "description": "The Volkswagen Vento has 1 Diesel Engine and 3 Petrol Engine on offer. The Diesel engine is 1498 cc while the Petrol engine is 999 cc and 1598 cc and 1197 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the Vento has a mileage of 16.09 to 22.27 kmpl & Ground clearance of Vento is 163 mm. The Vento is a 5 seater 3 cylinder car and has length of 4390mm, width of 1699mm and a wheelbase of 2553mm.",
    "brand": "Volkswagen",
    "image": "vento.webp",
    "fuel" : "petrol/diesel",
    "capacity":"55 litres.",
    "bodytype":"Sedan",
    "xpower":"108.62bhp@5000-5500rpm",
    "cylinders":"3 cylinder",
    "seating":"5 seater",
    "mileage":"16.35 kmpl",
    "torque":"175Nm@1750-4000rpm",
    "engin":"999 cc"
},{
    "id": 55,
    "title": "Volkswagen-Virtus",
    "price": "Rs.11.56 - 19.41",
    "description": "The Volkswagen Virtus has 2 Petrol Engine on offer. The Petrol engine is 999 cc and 1498 cc . It is available with Manual & Automatic transmission.Depending upon the variant and fuel type the Virtus has a mileage of 18.12 to 20.8 kmpl & Ground clearance of Virtus is 179 mm. The Virtus is a 5 seater 4 cylinder car and has length of 4561 mm, width of 1752 mm and a wheelbase of 2741.",
    "brand": "Volkswagen",
    "image": "virtus.webp",
    "fuel" : "Petrol",
    "capacity":"45 Litres",
    "bodytype":"Sedan",
    "xpower":"147.51bhp@5000-6000rpm",
    "cylinders":"4 cylinder",
    "seating":"5 seater",
    "mileage":"19.62 kmpl",
    "torque":"250Nm@1600-3500rpm",
    "engin":"1498 cc"
},{
    "id": 56,
    "title": "Koenigsegg-Agera",
    "price": "120000000",
    "description": "The Koenigsegg Agera has 1 Petrol Engine on offer. The Petrol engine is 4695 cc . It is available with the Automatic transmission.",
    "brand": "Koenigsegg ",
    "image": "agera.webp",
    "fuel" : "Petrol",
    "capacity":"80 Litres",
    "bodytype":"Coupe",
    "xpower":" 1,360 PS (1,000 kW;1,341 hp) at 7,500 rpm",
    "cylinders":"",
    "seating":"seater",
    "mileage":"8 kmpl",
    "torque":"1,371 N⋅m (1,011 lb⋅ft) of torque at6,000 rpm.",
    "engin":" 4695 cc"
},{
    "id": 57,
    "title": "AstonMartin-DBS710",
    "price": "13000000",
    "description": "The Aston Martin DBS has 1 Petrol Engine on offer. The Petrol engine is 5935 cc . It is available with Automatic transmission.Depending upon the variant and fuel type the DBS has a mileage of 8 kmpl . The DBS is a 2 seater 12 cylinder car and has length of 4721mm, width of 2060mm and a wheelbase of 2740mm.",
    "brand": "AstonMartin",
    "image": "dbs.webp",
    "fuel" : "petrol",
    "capacity":"80 Litres",
    "bodytype":"sedan",
    "xpower":"510bhp@6500rpm",
    "cylinders":"12 cylinder",
    "seating":"2 seater",
    "mileage":"8 kmpl",
    "torque":"570Nm@5750rpm",
    "engin":"5935 cc"
},{
    "id": 58,
    "title": "Audi-R8",
    "price": "27200000",
    "description": "The Audi R8 has 1 Petrol Engine on offer. The Petrol engine is 5204 cc . It is available with Automatic transmission.Depending upon the variant and fuel type the R8 has a mileage of 5.71 kmpl & Ground clearance of R8 is 110 mm. The R8 is a 2 seater 10 cylinder car and has length of 4426mm, width of 1940mm and a wheelbase of 2650mm.",
    "brand": "Audi",
    "image": "r8.webp",
    "fuel" : "Petrol",
    "capacity":"73 Litres",
    "bodytype":"Coupe",
    "xpower":"602bhp@8250rpm",
    "cylinders":"10 cylinder",
    "seating":"2 seater",
    "mileage":"5.71 kmpl",
    "torque":"560Nm@6500rpm",
    "engin":"5204 cc"
},{
    "id": 59,
    "title": "Ford Mustang",
    "price": "Rs.80 ",
    "description": "The Ford Mustang has 1 Petrol Engine on offer. The Petrol engine is 4999 cc . It is available with the Manual transmission.",
    "brand": "Ford",
    "image": "mustang.webp",
    "fuel" : "Petrol",
    "capacity":"",
    "bodytype":"Coupe",
    "xpower":"	396 bhp @ 6500 rpm",
    "cylinders":"8 cylinder",
    "seating":"5 seater",
    "mileage":"	7.9 kmpl",
    "torque":"625nm",
    "engin":"4999 cc"
},{
    "id": 60,
    "title": "Mercedes-Benz Maybach S-Class",
    "price": "Rs.2.72 - 3.43 Cr",
    "description": "The Mercedes-Benz Maybach S-Class has 2 Petrol Engine on offer. The Petrol engine is 3982 cc and 5980 cc . It is available with Automatic transmission.Depending upon the variant and fuel type the Maybach S-Class has a mileage of . The Maybach S-Class is a 5 seater 12 cylinder car and has length of 5469 mm, width of 2109 mm and a wheelbase of 3008.",
    "brand": "Mercedes",
    "image": "maybach.webp",
    "fuel" : "Petrol",
    "capacity":"80 litres",
    "bodytype":"Sedan",
    "xpower":"603.46bhp@5250-5500rpm",
    "cylinders":"12 cylinder",
    "seating":" 5 seater",
    "mileage":"7.50 - 9.80 kmpl",
    "torque":"900Nm@2000-4000rpm",
    "engin":"5980 cc"
},{
    "id": 61,
    "title": "Lexus LX570",
    "price": "23300000 cr",
    "description": "The LX 570 seats up to 8 people comfortably and is powered by a V8 5.7-liter direct injection engine that delivers 362 horsepower and control without compromise.",
    "brand": "Lexus",
    "image": "lx.webp",
    "fuel" : "Petrol",
    "capacity":"138 Litres",
    "bodytype":"SUV",
    "xpower":"362bhp@5600rpm",
    "cylinders":"8 cylinder",
    "seating":"8 seater",
    "mileage":"6.9 kmpl",
    "torque":"530Nm@3200rpm",
    "engin":"5663 cc"
},{
    "id": 62,
    "title": " Mercedes-Benz G-Class",
    "price": "25500000 cr",
    "description": "The Mercedes-Benz G-Class has 1 Diesel Engine and 1 Petrol Engine on offer. The Diesel engine is 2925 cc while the Petrol engine is 3982 cc . It is available with Automatic transmission.Depending upon the variant and fuel type the G-Class has a mileage of 8.47 kmpl . The G-Class is a 5 seater 8 cylinder car and has length of 4817 mm and width of 1931 mm.",
    "brand": "Mercedes",
    "image": "gwagon.webp",
    "fuel" : "Petrol",
    "capacity":"100 Litres",
    "bodytype":"SUV",
    "xpower":"576.63bhp",
    "cylinders":"8 cylinder",
    "seating":"5 seater",
    "mileage":"8.47 kmpl",
    "torque":"850Nm",
    "engin":"3982 cc"
},{
    "id": 63,
    "title": "Bugatti Chiron",
    "price": "Rs.19.21 - 28.40 cr",
    "description": "The Bugatti Chiron has 2 Petrol Engine on offer. The Petrol engine is 7993 cc and 7998 cc . It is available with the Automatic transmission.",
    "brand": "Bugatti ",
    "image": "chiron.webp",
    "fuel" : "Petrol",
    "capacity":"100 Litres",
    "bodytype":"Coupe",
    "xpower":"1479bhp@6700rpm",
    "cylinders":"16 cylinder",
    "seating":"2 seater",
    "mileage":"	5.95 kmpl",
    "torque":"1600Nm@2000-6000rpm",
    "engin":"7993 cc"
},{
    "id": 64,
    "title": "BMW-i8",
    "price": " 21400000 cr",
    "description": "The BMW i8 has 1 Petrol Engine on offer. The Petrol engine is 1499 cc . It is available with Automatic transmission.Depending upon the variant and fuel type the i8 has a mileage of 47.45 kmpl & Ground clearance of i8 is 117 mm. The i8 is a 4 seater 3 cylinder car and has length of 4689mm, width of 2218mm and a wheelbase of 2850mm.",
    "brand": "BMW",
    "image": "i8.webp",
    "fuel" : "Petrol",
    "capacity":"42 Litres",
    "bodytype":"Hybrid",
    "xpower":"228bhp@5800rpm",
    "cylinders":"3 cylinder",
    "seating":"4 seater",
    "mileage":" 47.45 kmpl",
    "torque":"320Nm@3700rpm",
    "engin":"1499 cc"
},{
    "id": 65,
    "title": "Bentley-Continental GT",
    "price": "35800000 cr",
    "description": "",
    "brand": "Bentley ",
    "image": "gt.webp",
    "fuel" : "Petrol",
    "capacity":"90 Litres",
    "bodytype":"Coupe",
    "xpower":"626bhp@5000-6000rpm",
    "cylinders":"12 cylinder",
    "seating":"4 seater",
    "mileage":"10.1 kmpl",
    "torque":"900Nm@1350-4500rpm",
    "engin":"1500cc"
},{
    "id": 66,
    "title": "Lamborghini-Urus",
    "price": "41800000 cr",
    "description": "The Lamborghini Urus stands as a testament to Lamborghini's unwavering dedication to pushing the boundaries of what's possible in the world of luxury and performance. It's a true embodiment of the brand's values, combining the power and precision of a supercar with the versatility and comfort of an SUV.",
    "brand": "Lamborghini",
    "image": "urus.jpg",
    "fuel" : "Petrol",
    "capacity":"100 Litres",
    "bodytype":"SUV",
    "xpower":"657bhp",
    "cylinders":"8",
    "seating":"5 seater",
    "mileage":"12kmpl",
    "torque":"760Nm@1200-4000rpm",
    "engin":"2100cc"
},{
    "id": 67,
    "title": "Rolls-Royce-Phantom",
    "price": "14800000 cr",
    "description": "Rolls-Royce Holdings plc is a British multinational aerospace and defence company incorporated in February 2011. The company owns Rolls-Royce, a business established in 1904 which today designs, manufactures and distributes power systems for aviation and other industries.",
    "brand": "Rolls-Royce",
    "image": "phantom.jpg",
    "fuel" : "Petrol",
    "capacity":"100 litres",
    "bodytype":"Sedan",
    "xpower":"563bhp",
    "cylinders":"12",
    "seating":"2 seater",
    "mileage":"9kmpl",
    "torque":"900Nm",
    "engin":"6749cc"
},{
    "id": 68,
    "title": "Pagani-Huayra",
    "price": "150000000",
    "description": "The Pagani Huayra is different from its predecessor in that it incorporates active aerodynamics. It is capable of changing the height of the front from the ground and independently operating four flaps placed at the rear and front of the car. The behavior of the flaps is managed by a dedicated control unit that is fed information from systems such as the ABS and ECU, which pass on information about the car's speed, yaw rate, lateral acceleration, steering angle and throttle position.",
    "brand": "Pagani",
    "image": "pagani.jpg",
    "fuel" : "Petrol",
    "capacity":"100 litres",
    "bodytype":"Sedan",
    "xpower":"760bhp",
    "cylinders":"12",
    "seating":"2 seater",
    "mileage":"10kmpl",
    "torque":"920Nm",
    "engin":"6732cc"
},{
    "id": 69,
    "title": "Porsche-911-GT3RS",
    "price": "27500000",
    "description": "Athletes know: top performance requires more than perfect conditions and luck. Relentless training to become stronger and faster. Questioning everything, especially yourself. Learning from every mistake. Because the biggest challenge is to remain unbeatable. With this attitude, Porsche keeps pushing the boundaries of what is possible. Experience the new 911 GT3 RS in top form - with increased race track performance.",
    "brand": "Porsche",
    "image": "911.jpg",
    "fuel" : "Petrol",
    "capacity":"64 litres",
    "bodytype":"Coupe",
    "xpower":"502bhp",
    "cylinders":"6",
    "seating":"2 seater",
    "mileage":"11kmpl",
    "torque":"470Nm",
    "engin":"3996cc"
},{
    "id": 70,
    "title": "Ferrari-Roma",
    "price": "37600000",
    "description": "The Ferrari Roma, the new mid-front-engined 2+ coupé of the Prancing Horse, features refined proportions and timeless design combined with unparalleled performance and handling. With its distinctive flair and style, the car is a contemporary representation of the carefree, pleasurable way of life that characterised Rome in the 1950s and ‘60s.",
    "brand": "Ferrari",
    "image": "roma.jpg",
    "fuel" : "Petrol",
    "capacity":"80 litres",
    "bodytype":"Coupe",
    "xpower":"611.2bhp",
    "cylinders":"10",
    "seating":"2 seater",
    "mileage":"8.3kmpl",
    "torque":"760Nm",
    "engin":"3855cc"   
}]